import smtplib
from email.message import EmailMessage
import os

# IMPORTANT: Put your email and the 16-letter App Password here!
SENDER_EMAIL = "your.email@gmail.com" 
SENDER_PASSWORD = "your-16-letter-app-password"

def send_alert_email(target_department: str, recipient_email: str, analysis_id: int, pdf_path: str, score: float):
    """Drafts an email, attaches the PDF report, and sends it to the authorities."""
    
    msg = EmailMessage()
    msg['Subject'] = f"CRITICAL ALERT: RiverSense AI Biodiversity Report (ID: {analysis_id})"
    msg['From'] = SENDER_EMAIL
    msg['To'] = recipient_email

    # The actual email text
    body = f"""
    Dear {target_department},

    The RiverSense AI early-warning system has detected a critical environmental event.
    
    Current Biodiversity Health Score: {score}/100
    
    Please find the attached automated conservation report containing the specific pollution indicators and endangered species warnings. Immediate action is recommended.

    System Generated by RiverSense AI.
    """
    msg.set_content(body)

    # Attach the PDF Document safely
    if os.path.exists(pdf_path):
        with open(pdf_path, 'rb') as f:
            pdf_data = f.read()
            pdf_name = os.path.basename(pdf_path)
            
        msg.add_attachment(pdf_data, maintype='application', subtype='pdf', filename=pdf_name)
    else:
        print(f"Warning: PDF not found at {pdf_path}")

    # Send the email via Gmail's SMTP server
    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
            smtp.login(SENDER_EMAIL, SENDER_PASSWORD)
            smtp.send_message(msg)
        print(f"Success: Alert emailed to {target_department} at {recipient_email}")
        return True
    except Exception as e:
        print(f"Failed to send email: {e}")
        return False